export default {
  common: {
    confirm: '确认',
    cancel: '取消',
    save: '保存',
    delete: '删除',
    add: '添加',
    search: '搜索',
    close: '关闭',
    loading: '加载中...',
    error: '错误',
    success: '成功',
    empty: '暂无数据',
  },
  menu: {
    stock: '股票',
    profile: '个人中心',
    admin: '管理',
    users: '用户管理',
    sync: '数据同步',
    logout: '退出登录',
  },
  login: {
    title: 'Stock Analysis',
    username: '用户名',
    password: '密码',
    login: '登录',
    failed: '登录失败',
  },
  stockList: {
    title: '我的持仓',
    addStock: '添加股票',
    code: '代码',
    note: '备注',
    action: '操作',
    detail: '详情',
    selectStock: '请选择股票',
    added: '添加成功',
  },
  stockDetail: {
    basic: '基础与价差',
    statistics: '详细统计',
    industry: '行业',
    listDate: '上市日期',
    lastClose: '最近收盘',
    spreads: '价差分布',
    dailyBars: '日线数据',
    date: '日期',
    open: '开盘',
    high: '最高',
    low: '最低',
    close: '收盘',
    vol: '成交量',
    oh: '高-开',
    ol: '开-低',
    hl: '高-低',
    oc: '开-收',
    hc: '高-收',
    lc: '低-收',
    draft: '今日草稿',
    draftSave: '保存草稿',
    draftApply: '应用',
    modelTable: '价差模型',
    tradePlan: '交易计划',
    predictions: '预测记录',
    recalc: '重新计算',
    recalcDone: '重算完成',
    timePeriod: '时段',
    window: '时段',
    predictHigh: '预测高',
    predictLow: '预测低',
    actualHigh: '实际高',
    actualLow: '实际低',
    devHigh: '偏差',
    devLow: '偏差',
  },
  profile: {
    title: '个人中心',
    info: '个人信息',
    username: '用户名',
    role: '角色',
    registeredAt: '注册时间',
    changePassword: '修改密码',
    oldPassword: '原密码',
    newPassword: '新密码',
    passwordChanged: '密码已修改',
    tushareToken: 'Tushare Token',
    tokenSaved: 'Token 已保存',
    apiTokens: 'API Tokens',
    tokenName: '名称',
    createdAt: '创建时间',
    createToken: '新建 Token',
    tokenCreated: '创建成功',
    revoke: '撤销',
    revoked: '已撤销',
    copyPrompt: '请立即复制，只会显示一次',
  },
  admin: {
    users: '用户管理',
    sync: '数据同步',
    createUser: '新建用户',
    status: '状态',
    enabled: '正常',
    disabled: '禁用',
    toggle: '切换',
    syncStocklist: '同步股票列表',
    syncBars: '同步行情数据',
    job: '任务',
    startedAt: '开始时间',
    finishedAt: '结束时间',
  },
}
